apiVersion: v1
kind: Service
metadata:
  name: hadoop-master
spec:
  ports:
    - name: metadata
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: web
      port: 50070
      targetPort: 50070
      protocol: HTTP
  selector:
    service: hadoop-master
