apiVersion: v1
kind: Service
metadata:
  name: hadoop-master
spec:
  type: NodePort
  ports:
    - name: metadata
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: web
      port: 50070
      targetPort: 50070
      nodePort: 30080
      protocol: TCP
  selector:
    service: hadoop-master
