apiVersion: v1
kind: Service
metadata:
  name: hadoop-slave
  labels:
    service: hadoop-slave
spec:
  ports:
    - name: web
      port: 50075
      targetPort: 50075
      protocol: HTTP
  selector:
    service: hadoop-slave
